name: Build Containers
on:
  push:
    branches: ["main"]
  workflow_dispatch:
jobs:
  build_and_release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}
      - name: Build and Push
        run: |
          docker build . --tag ghcr.io/devramsean0/tsy_disruptor_detector:latest
          docker push ghcr.io/devramsean0/tsy_disruptor_detector:latest
